FROM ubuntu:24.04

RUN apt update && apt install -y \
    xcb \
    libxcb-* \
    libxkbcommon-x11-0 \
    less \
    libxkbcommon0 \
    libx11-xcb1 \
    libfreetype6 \
    libfontconfig1 \
    libdbus-1-3 \
    ca-certificates \
    libglib-2.0-0 \
    git \
    build-essential \
    cmake \
    libgl1 \
    libgl1-mesa-dev 

WORKDIR /root
RUN echo 'export PATH=/opt/Qt/6.9.0/gcc_64/bin:$PATH' >> /root/.bashrc

COPY --from=src ./qt-online-installer-linux-x64-4.9.0.run /root/
COPY --from=src ./install.sh /root/

RUN chmod +x qt-online-installer-linux-x64-4.9.0.run install.sh 

CMD ["sleep", "infinity"]
